### ISSUE TITLE
Guru Claim Request: Sunshine

### ISSUE THREAD

**Issue by ReenigneArcher** [Gurubase/gurubase#24]
**Gurubase Username:** 

reenignearcher@redacted (Logged in with GitHub OAuth, and can't change username)

**Guru Link:** 

https://gurubase.io/g/sunshine

**Proof of Maintainership:** 

Merged PRs: https://github.com/LizardByte/Sunshine/issues?q=is%3Apr%20author%3AReenigneArcher%20is%3Amerged

**Comment by ReenigneArcher** [comment]
Linking guru PR: https://github.com/LizardByte/Sunshine/pull/3466

**Comment by kursataktas** [comment]
Hey @ReenigneArcher 

I’ve assigned it to your Gurubase account. You can find it on the 'My Gurus' page. While I’m closing this issue, please let me know if you need any help here or on our [Discord Channel](https://discord.gg/9CMRSQPqx6).
